version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "3308:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
    ports:
      - "8080:8080"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVICES=iam,s3,lambda,stepfunctions,dynamodb
      - LAMBDA_EXECUTOR=docker
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - BACKEND_URL=http://host.docker.internal:3001
    ports:
      - "4566:4566"
      - "4572:4572"
    volumes:
      - ./lambdas:/var/task
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pg_data:
  localstack_data:
  qdrant_storage: